services:
  backend:
    build: 
      context: ${LARAVEL}
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_LARAVEL}
    restart: unless-stopped
    volumes:
      - ${LARAVEL}/:/var/www/html
    depends_on:
      - db
    networks:
      - weft-network
  reverb:
    build: 
      context: ${LARAVEL}
      dockerfile: Dockerfile
    container_name: reverb
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ${LARAVEL}/:/var/www/html
    networks:
      - weft-network
    command: ["php", "artisan", "reverb:start"]  
    depends_on:
      - backend  
  frontend:
    build: 
      context: ${REACT}
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_REACT}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - weft-network
  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME_NGINX}
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${LARAVEL}/public:/var/www/html/public
      - ${REACT}/dist:/var/www/frontend/dist
    depends_on:
      - backend
      - frontend 
      - reverb
    networks:
      - weft-network
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - weft-network
  db:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - weft-network
    ports:
      - "${MYSQL_PORT}:3306"
networks: 
  weft-network:
    driver: bridge
volumes:
  db_data:
    driver: local